version: "3.9"

services:
  db:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: db
      DB_PORT: "3318"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RCON_PORT: ${RCON_PORT}
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_HOST: ${RCON_HOST}
      BOT_TOKEN: ${BOT_TOKEN}
      TARGET_CHAT_ID: ${TARGET_CHAT_ID}

volumes:
  db_data:
